#!/bin/bash -ue

if [ ${#@} -lt 2 ] || [ -z "${1-}" ] || [ -z "${2-}" ]; then
    echo "$0: Must specify a version." >&2
    echo "  In a shebang: #!/L/python 3.8" >&2
    echo "  Directly: /L/python 3.8 -m json.tool" >&2
    exit 1
fi

PVER="python${1}"

if ! dpkg -l "${PVER}" >/dev/null 2>&1; then
    if ! (/L/apt-ish install -y "${PVER}") >/dev/null; then
        echo "$0: Failed to apt-get ${PVER}" >&2
        exit 1
    fi
fi

shift

"${PVER}" "$@"
